#!/bin/bash

file=$1
line_number=`expr "$file" : '.*:\([0-9]\+\)'`

if [[ "$line_number" == "" ]] ; then
	exec vim "$*"
else
	file=${file%%:$line_number*}
	shift

	exec vim "$file" +$line_number $*
fi
